dist: trusty
sudo: false
language: rust
rust:
- nightly
- beta
- stable
addons:
  apt:
    packages:
    - libasound2-dev
    - libgdk-pixbuf2.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libnotify-dev
    - libx11-dev
    - pkg-config
    # for build.sh
    - gperf
    - libegl1-mesa-dev
    - libfreetype6-dev
    - libmount-dev
    - libpng-dev
    - libxml-parser-perl
    - libxtst-dev
    - xutils-dev
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  ./.travis/build.sh
  # travis-cargo test &&
  # travis-cargo --only stable doc
# after_success:
# - travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  # - secure:
