dist: trusty
sudo: false
language: rust
rust:
- nightly
- beta
- stable
addons:
  apt:
    sources:
    - sourceline: 'ppa:gnome3-team/gnome3-staging'
    - sourceline: 'ppa:gnome3-team/gnome3'
    packages:
    - libasound2-dev
    - libgdk-pixbuf2.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libnotify-dev
    - libpng-dev
    - libx11-dev
    - pkg-config
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build
  # travis-cargo test &&
  # travis-cargo --only stable doc
# after_success:
# - travis-cargo --only stable doc-upload
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  # - secure:
